version: '3.6'

services:
  laradra:
    image: ghcr.io/mileschou/php-tester:8.0
    working_dir: /app
    command: ["php", "laradra"]
    environment:
      HYDRA_CLIENT_ID: some-client
      HYDRA_CLIENT_SECRET: some-secret
      HYDRA_REDIRECT_URI: http://web.localhost:8080/rp/callback
      HYDRA_ADMIN_URL: http://hydra.localhost:4445
      HYDRA_PUBLIC_URL: http://hydra.localhost:4444
    volumes:
      - .:/app:delegated
    depends_on:
      - hydra

  hydra:
    image: oryd/hydra:v2.1.0
    container_name: hydra.localhost
    hostname: hydra.localhost
    ports:
      - "4444:4444"
      - "4445:4445"
    command:
      serve all --dev
    environment:
      DSN: mysql://root:secret@tcp(mysqld:3306)/hydra?max_conns=20&max_idle_conns=4
      URLS_SELF_ISSUER: http://hydra.localhost:4444
      URLS_LOGIN: http://web.localhost:8080/provider/login
      URLS_CONSENT: http://web.localhost:8080/provider/consent
      URLS_LOGOUT: http://web.localhost:8080/provider/logout
      TTL_ACCESS_TOKEN: 24h
      SECRETS_SYSTEM: youReallyNeedToChangeThis
      OIDC_SUBJECT_TYPES_SUPPORTED: public,pairwise
      OIDC_SUBJECT_TYPE_PAIRWISE_SALT: youReallyNeedToChangeThis
    restart: unless-stopped
    depends_on:
      - hydra-migrate

  hydra-migrate:
    image: oryd/hydra:v2.1.0-arm64
    environment:
      - DSN=mysql://root:secret@tcp(mysqld:3306)/hydra?max_conns=20&max_idle_conns=4
    command:
      migrate sql -e --yes
    restart: on-failure
    depends_on:
      mysqld:
        condition: service_healthy

  mysqld:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: hydra
    healthcheck: # Ref: https://github.com/laravel/framework/blob/8.x/.github/workflows/tests.yml
      test: mysqladmin ping --password=secret
      interval: 10s
      timeout: 5s
      retries: 3
